version: 0.2

phases:
  pre_build:
    commands:
      - docker build -t helloworld submodule
  build:
    commands:
      - docker images
      - docker run helloworld echo "Hello, World!" 
      